### ISSUE TITLE
1.8.0 should have been 2.0.0

### ISSUE THREAD

**Issue by stevenroussey-privicy** [keeweb/kdbxweb#35]
v1.8 switches to v4 file format, and v4 file format requires Argon2, thus a breaking change.

**Comment by stevenroussey-privicy** [comment]
Also, sample code for using node-argon2, sodium-native, and a wasm implementation would be great.

**Comment by antelle** [comment]
Hi! KeeWeb has been supporting KDBXv4 for more than three years. Also we don't strictly follow semver and assign versions in more a common sense rather than breaking/non-breaking changes. So that a bigger change like whole UI or technology redesign would be 2.0, while small things like default file format no.

**Comment by antelle** [comment]
Just realized that that issue is in kdbxweb, not keeweb. However same applies, KDBXv4 has been supported for a long time and it shouldn't be a breaking change.
